name: Development CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: ./.github/actions/setup-node
      - name: cache node_modules
        uses: ./.github/actions/cache-node-modules

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: ./.github/actions/setup-node
      - name: cache node_modules
        uses: ./.github/actions/cache-nodemodules

      - name: Lint check
        run: yarn lint:check

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: ./.github/actions/setup-node
      - name: cache node_modules
        uses: ./.github/actions/cache-nodemodules

      - name: Test
        run: yarn test:run

  chromatic:
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node
        uses: ./.github/actions/setup-node
      - name: cache node_modules
        uses: ./.github/actions/cache-node-modules
